[[],
 [],
 [],
 [],
 [],
 [{"Status"=>"running", "System"=>"localhost"}],
 [{"Status"=>"not monitored", "Process"=>"tomcat", "Uptime"=>"-"},
  {"Status"=>"not monitored", "Process"=>"proxr", "Uptime"=>"-"},
  {"Status"=>"not monitored", "Process"=>"nginx", "Uptime"=>"-"},
  {"Status"=>"Execution failed", "Process"=>"munin", "Uptime"=>"-"},
  {"Status"=>"not monitored", "Process"=>"haproxy", "Uptime"=>"-"},
  {"Status"=>"running", "Process"=>"filer", "Uptime"=>"3d 0h 24m "}],
 [{"Inodes usage"=>"- [-]",
   "Status"=>"Does not exist",
   "Device"=>"disk1",
   "Space usage"=>"- [-]"},
  {"Inodes usage"=>"- [-]",
   "Status"=>"Does not exist",
   "Device"=>"disk2",
   "Space usage"=>"- [-]"},
  {"Inodes usage"=>"- [-]",
   "Status"=>"Does not exist",
   "Device"=>"disk3",
   "Space usage"=>"- [-]"}]]